apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-conf
data:
  host: mysqldb
  dbname: springapp
  password: root
  user: root
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:                      
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend    
  labels:                     
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: rihabab/spring2:latest
        ports:
        - containerPort: 8080
          name: backend-port
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
          requests:
            memory: "250Mi"
            cpu: "250m"
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-conf
              key: host
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-conf
              key: dbname
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-conf
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mysql-conf
              key: password
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 200
          timeoutSeconds: 10
          periodSeconds: 30     

       
