kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: simple-binding
  namespace: exam
subjects:
- kind: User
  name: user1
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: simple-user
  apiGroup: rbac.authorization.k8s.io
