# utilisation de l'image maven pour la construction
FROM maven AS build

# Définitir la répertoire de travaille
WORKDIR /app/myapp

# Copie du code source dans l'image de construction
COPY . .

# Construction du projet avec Maven
RUN mvn clean package -DskipTests

# Image pour ranner le code java
FROM openjdk:17-alpine

# Définitir la répertoire de travaille
WORKDIR /app

EXPOSE 8080

# Copie du fichier JAR généré depuis l'étape de construction
COPY --from=build /app/myapp/target/spring-boot-data-jpa-0.0.1-SNAPSHOT*.jar spring-boot-data-jpa-0.0.1-SNAPSHOT.jar

# Commande à exécuter lors du démarrage du conteneur
ENTRYPOINT ["java","-jar","spring-boot-data-jpa-0.0.1-SNAPSHOT.jar"]

# Run the application when the container launches


# FROM openjdk:22-ea-jdk-bookworm

# WORKDIR /app

# COPY target/ .

# EXPOSE 8080

# CMD ["java", "-jar", "spring-boot-data-jpa-0.0.1-SNAPSHOT.jar", "--spring.config.location=classes/application.properties"]